### PR TITLE
Chris/refactoring

### PR DESCRIPTION
**Pull request by ChristianMarchetta**
This branch contains several refactors to:
- remove dead code 
- converting js functions which return JSX or TSX into React components
- abstracting logic into React hooks

### CODE REVIEW

**Review by reteppeter — APPROVED** [review]

**Comment by ChristianMarchetta** [comment]
Be carefull while reviewing as I had to solve several merge conflicts and I'm not sure if I broke anything.

For example this happens when the page has a medium width (tablet mode), but it looks good on desktop
image

**Review by reteppeter — COMMENTED** [review]
Good (but someone else should review it).

**Review by reteppeter — APPROVED** [review]

**Comment by mt-empty** [comment]
@ChristianMarchetta , could you resolve the issues?

**Comment by ChristianMarchetta** [comment]
> @ChristianMarchetta , could you resolve the issues?

@mt-empty I merged the conflicts and fixed some linting problems.

There still are two failing test cases in `semVer.test.ts`, I think it might be faster for @alexdelicato or @reteppeter to fix them as I am not as familiar with semVer strings and the functions in `src/semVer.ts`

**Pull request merged**
