### PR TITLE
Changed small clickable icons

### PR DESCRIPTION
**Pull request by ChristianMarchetta**
Ensuring all clickable items are 44x44px or more.
Changes made:
1. Enlarged buttons in the "Total Repositories" box
2. Aligned the three box headers and sub-boxes 
image
4. Enlarged Grid Row expand arrow icon. Note, this is actuall 40x40px, because enlarging it more makes each row considerably thicker
image
 
There are some other clickable items that are lower than 44px in one dimension, but longer in the other dimension, such as 
image
I left these untouched, let me know if these should be enlarged as well.

# TODO:
I need someone to run precommit hooks for me before merging 💕

### CODE REVIEW

**Comment by leanne-b** [comment]
The question mark button seems to be overflowing into the margin/padding border ? 
image

**Comment by leanne-b** [comment]
In response to "3. Enlarged Grid Row expand arrow icon. Note, this is actuall 40x40px, because enlarging it more makes each row considerably thicker"
I think its ok to make each row thicker for mobile, as long as it's more usable 44x44px standard is good.
Please make the other buttons larger to meet 44x44px accessibility standard  too. 

Also is it possible to apply this fix to desktop too?
image

**Comment by ChristianMarchetta** [comment]
> Also is it possible to apply this fix to desktop too?

You mean the overflowing question mark button fix?

**Comment by ChristianMarchetta** [comment]
@leanne-b  Should be all fixed now

**Comment by leanne-b** [comment]
> 

No like aligning the 3 boxes and sub boxes

**Comment by ChristianMarchetta** [comment]
Aren't them already aligned? It's just the bottom margin of the inner boxes that is not aligned, but that's very difficult to align

**Comment by ChristianMarchetta** [comment]
Summary container alignment should be fixed for large screens as well now
image

Though, there still is the very difficult to solve problem that the "Total Repositories" text overlaps right after the large screen break point, but then becomes as in the screenshot above.
image


I think the current solution is good enough to merge, boxes are aligned for all screen sizes except for a short window right after the large break point, in which case the result is not super ugly to look at.

**Comment by ChristianMarchetta** [comment]
I think running precommits should fix the failing checks

**Review by Akshith-Patil — APPROVED** [review]

**Pull request merged**
